import '../models/content_pack.dart';
import '../models/game_mode.dart';
import '../models/tile.dart';

class TileCatalog {
  static const List<Tile> universal = [
    Tile(id: 101, type: TileType.drink, text: 'Bebe 1 trago'),
    Tile(id: 102, type: TileType.drink, text: 'Bebe 2 tragos'),
    Tile(id: 103, type: TileType.drink, text: 'Bebe 3 tragos'),
    Tile(id: 104, type: TileType.drink, text: 'Bebe 4 tragos'),
    Tile(id: 105, type: TileType.drink, text: 'Bebe tantos tragos como letras tenga tu nombre'),
    Tile(id: 106, type: TileType.drink, text: 'Bebe 2 tragos por cada vocal de tu nombre'),
    Tile(id: 107, type: TileType.groupDrink, text: 'Brindis obligatorio. Beben todos'),
    Tile(id: 108, type: TileType.groupDrink, text: 'Los dos jugadores con menos tragos beben 1'),
    Tile(id: 109, type: TileType.groupDrink, text: 'Los que lleven colores oscuros beben 2'),
    Tile(id: 111, type: TileType.chaos, text: 'Elige quién bebe 4 tragos'),
    Tile(id: 112, type: TileType.chaos, text: 'El último en ponerse de pie bebe 3 tragos'),
    Tile(id: 113, type: TileType.chaos, text: 'Intercambia la bebida con la persona de tu derecha'),
    Tile(id: 114, type: TileType.chaos, text: 'El más serio bebe 2. Lo decide el grupo'),
    Tile(id: 115, type: TileType.chaos, text: 'Reparte 4 tragos como quieras'),
    Tile(id: 116, type: TileType.rule, text: 'Nueva regla'),
    Tile(id: 117, type: TileType.rule, text: 'Nueva regla'),
    Tile(id: 118, type: TileType.rule, text: 'Nueva regla'),
    Tile(id: 119, type: TileType.chaos, text: 'El jugador anterior a ti bebe 3 tragos'),
    Tile(id: 120, type: TileType.chaos, text: 'Reparte 4 tragos como quieras entre los jugadores'),
    Tile(id: 801, type: TileType.wildcard, text: 'Comodín: el grupo inventa un reto ahora mismo'),
    Tile(id: 802, type: TileType.wildcard, text: 'Comodín: el jugador a tu izquierda decide qué haces'),
    Tile(id: 803, type: TileType.wildcard, text: 'Comodín: el grupo vota un reto para ti. Lo que diga la mayoría, va'),
  ];

  static const List<Tile> light = [
    Tile(id: 501, type: TileType.social, mode: GameMode.light, category: TileCategory.truth, text: 'Verdad: cuenta la anécdota más absurda que te haya pasado de fiesta'),
    Tile(id: 502, type: TileType.social, mode: GameMode.light, category: TileCategory.dare, text: 'Reto: habla durante una ronda con voz de locutor o bebe 2'),
    Tile(id: 503, type: TileType.social, mode: GameMode.light, category: TileCategory.neverHaveIEver, text: 'Nunca nunca: el que lo haya hecho bebe 2 tragos'),
    Tile(id: 504, type: TileType.social, mode: GameMode.light, category: TileCategory.actOut, text: 'Imitación: el grupo elige un famoso y tienes que imitarlo'),
    Tile(id: 505, type: TileType.social, mode: GameMode.light, text: 'Di algo bueno de cada jugador o bebe 1 por cada uno que te saltes'),
    Tile(id: 506, type: TileType.social, mode: GameMode.light, text: 'El de tu izquierda te pone un apodo para esta ronda'),
    Tile(id: 507, type: TileType.social, mode: GameMode.light, text: 'Cuenta tu peor chiste. Si nadie se ríe, bebe 2'),
    Tile(id: 508, type: TileType.social, mode: GameMode.light, text: '¿Quién acabaría antes perdiendo el móvil? El grupo decide'),
    Tile(id: 509, type: TileType.social, mode: GameMode.light, text: 'Confiesa un pequeño drama reciente o bebe 3'),
    Tile(id: 510, type: TileType.social, mode: GameMode.light, text: 'Haz una pose ridícula hasta que vuelva tu turno'),
    Tile(id: 511, type: TileType.social, mode: GameMode.light, text: 'La persona de tu derecha te hace una pregunta. Responde o bebe 3'),
    Tile(id: 512, type: TileType.social, mode: GameMode.light, text: 'Todos dicen una manía tuya. Si te enfadas, bebes 2'),
    Tile(id: 513, type: TileType.social, mode: GameMode.light, text: 'Haz reír al grupo. Si fallas, bebe 2'),
    Tile(id: 514, type: TileType.social, mode: GameMode.light, text: 'Di qué superpoder usarías esta noche y por qué, o bebe 2'),
    Tile(id: 515, type: TileType.social, mode: GameMode.light, text: 'La persona más puntual reparte 2 tragos'),
    Tile(id: 516, type: TileType.social, mode: GameMode.light, text: 'Cuenta una anécdota vergonzosa del cole o bebe 3'),
    Tile(id: 517, type: TileType.social, mode: GameMode.light, text: 'Todos señalan al más probable de montar una bronca. Ese bebe 2'),
    Tile(id: 518, type: TileType.social, mode: GameMode.light, text: 'Haz una mini actuación como camarero borde'),
  ];

  static const List<Tile> spicy = [
    Tile(id: 601, type: TileType.social, mode: GameMode.spicy, category: TileCategory.truth, text: 'Verdad: ¿qué mensaje te arrepientes más de haber enviado? Cuéntalo o bebe 3'),
    Tile(id: 602, type: TileType.social, mode: GameMode.spicy, category: TileCategory.dare, text: 'Reto: deja que el grupo elija tu foto de perfil hasta el próximo turno'),
    Tile(id: 603, type: TileType.social, mode: GameMode.spicy, category: TileCategory.neverHaveIEver, text: 'Nunca nunca picante: quien lo haya hecho bebe 3'),
    Tile(id: 604, type: TileType.social, mode: GameMode.spicy, category: TileCategory.actOut, text: 'Actuación: interpreta una cita desastrosa durante 20 segundos'),
    Tile(id: 605, type: TileType.social, mode: GameMode.spicy, text: 'Lee el último emoji que enviaste y explica el contexto o bebe 3'),
    Tile(id: 606, type: TileType.social, mode: GameMode.spicy, text: '¿Quién de aquí tiene más labia? El grupo decide'),
    Tile(id: 607, type: TileType.social, mode: GameMode.spicy, text: 'Confiesa tu peor cita o bebe 4'),
    Tile(id: 608, type: TileType.social, mode: GameMode.spicy, text: 'Todos votan en voz alta quién liga mejor. Esa persona reparte 3'),
    Tile(id: 609, type: TileType.social, mode: GameMode.spicy, text: 'Muestra la última búsqueda vergonzosa o bebe 3'),
    Tile(id: 610, type: TileType.social, mode: GameMode.spicy, text: 'Di quién de aquí te respondería antes a las 3 a.m. o bebe 2'),
    Tile(id: 611, type: TileType.social, mode: GameMode.spicy, text: 'Cuenta la mentira romántica más absurda que hayas dicho o bebe 3'),
    Tile(id: 612, type: TileType.social, mode: GameMode.spicy, text: 'Imita cómo ligarías con alguien del grupo sin decir su nombre, o bebe 3'),
    Tile(id: 613, type: TileType.social, mode: GameMode.spicy, text: 'Confiesa algo que aún te da vergüenza recordar o bebe 4'),
    Tile(id: 614, type: TileType.social, mode: GameMode.spicy, text: 'El grupo elige una app y debes abrir la última notificación recibida o beber 3'),
    Tile(id: 615, type: TileType.social, mode: GameMode.spicy, text: 'Di el nombre de la peor red flag que has ignorado o bebe 2'),
    Tile(id: 616, type: TileType.social, mode: GameMode.spicy, text: 'Haz una escena de celos totalmente exagerada o bebe 3'),
    Tile(id: 617, type: TileType.social, mode: GameMode.spicy, text: 'Todos dicen quién sería peor ex. El más nombrado bebe 2'),
    Tile(id: 618, type: TileType.social, mode: GameMode.spicy, text: 'Cuenta qué persona te ha dejado más en visto o bebe 2'),
  ];

  static const List<Tile> wild = [
    Tile(id: 701, type: TileType.social, mode: GameMode.wild, category: TileCategory.truth, text: 'Verdad extrema: cuenta la mayor locura que has hecho por orgullo, o bebe 4'),
    Tile(id: 702, type: TileType.social, mode: GameMode.wild, category: TileCategory.dare, text: 'Reto extremo: deja que el grupo te redacte un estado absurdo'),
    Tile(id: 703, type: TileType.social, mode: GameMode.wild, category: TileCategory.neverHaveIEver, text: 'Nunca nunca salvaje: quien lo haya hecho bebe 4'),
    Tile(id: 704, type: TileType.social, mode: GameMode.wild, category: TileCategory.actOut, text: 'Interpretación: actúa como villano de telenovela señalando a un traidor'),
    Tile(id: 705, type: TileType.social, mode: GameMode.wild, text: 'Di quién te cae peor en este momento o bebe 5'),
    Tile(id: 706, type: TileType.social, mode: GameMode.wild, text: 'El grupo te hace una pregunta y respondes sin filtro o bebes 5'),
    Tile(id: 707, type: TileType.social, mode: GameMode.wild, text: 'Confiesa la peor mentira que has sostenido demasiado tiempo, o bebe 4'),
    Tile(id: 708, type: TileType.social, mode: GameMode.wild, text: 'Enséñale al grupo la última foto que te dio vergüenza guardar o bebe 5'),
    Tile(id: 709, type: TileType.social, mode: GameMode.wild, text: 'Haz una imitación dramática de alguien famoso en pleno escándalo'),
    Tile(id: 710, type: TileType.social, mode: GameMode.wild, text: 'Todos señalan a quien sería más caótico como compañero de piso. Ese bebe 3'),
    Tile(id: 711, type: TileType.social, mode: GameMode.wild, text: 'Cuenta qué harías con 1000 euros si nadie pudiera juzgarte, o bebe 3'),
    Tile(id: 712, type: TileType.social, mode: GameMode.wild, text: 'Elige entre sinceridad total o beber 6'),
    Tile(id: 713, type: TileType.social, mode: GameMode.wild, text: 'Haz un discurso de ruptura inventado como si estuvieras en una película'),
    Tile(id: 714, type: TileType.social, mode: GameMode.wild, text: 'Di cuál ha sido tu peor impulso esta semana o bebe 3'),
    Tile(id: 715, type: TileType.social, mode: GameMode.wild, text: 'El grupo decide si tu historia es verdad o mentira. Si no te creen, bebes 4'),
    Tile(id: 716, type: TileType.social, mode: GameMode.wild, text: 'Cuenta la cosa más temeraria que harías por una apuesta o bebe 3'),
    Tile(id: 717, type: TileType.social, mode: GameMode.wild, text: 'Nombra a quien crees que se mete antes en un lío. Si coincide el grupo, bebe'),
    Tile(id: 718, type: TileType.social, mode: GameMode.wild, text: 'Actúa como si te hubieran pillado en una mentira gigantesca'),
  ];

  static const List<Tile> exToxico = [
    // SPICY
    Tile(id: 901, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Qué red flag viste clarísima y decidiste ignorar? Cuéntala o bebe 2'),
    Tile(id: 902, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Cuenta una discusión absurda que tuviste en pareja o bebe 2'),
    Tile(id: 903, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Alguna vez has cotilleado las redes de tu ex después de dejarlo? Confiesa o bebe 2'),
    Tile(id: 904, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Te han dejado o has dejado más veces? Explica o bebe 2'),
    Tile(id: 905, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Cuenta algo que hiciste en una relación que repetirías sin dudarlo, o bebe 2'),
    Tile(id: 917, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Cuánto tardaste en stalkear a tu ex después de la ruptura? Confiesa o bebe 2'),
    Tile(id: 918, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Has usado a alguien como rebote? Cuenta o bebe 2'),
    Tile(id: 919, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Alguna vez has fingido estar bien después de una ruptura? ¿Cuánto duró la farsa? Cuéntalo o bebe 2'),
    Tile(id: 920, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Has bloqueado y desbloqueado a alguien más de una vez? Explica por qué o bebe 2'),
    Tile(id: 921, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Cuenta la ruptura más cobarde que has tenido, dando o recibiendo, o bebe 2'),
    Tile(id: 922, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Has mandado un "feliz cumpleaños" a un ex solo para ver si respondía? Confiesa o bebe 2'),
    Tile(id: 923, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Alguna vez has puesto una canción en un plan para que alguien concreto la escuchara? Cuenta o bebe 2'),

    // WILD
    Tile(id: 906, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Volverías con tu ex si te escribe ahora mismo? Responde sin pensar o bebe 2'),
    Tile(id: 907, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta lo más rastrero que hiciste por celos o bebe 3'),
    Tile(id: 908, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿A quién de tus ex no soportas ver feliz? Di el nombre o bebe 3'),
    Tile(id: 909, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has hablado con alguien solo para dar celos? Cuenta o bebe 3'),
    Tile(id: 910, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta una mentira que dijiste en una relación de la que nunca se enteraron, o bebe 3'),
    Tile(id: 911, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has mirado el móvil de alguien a escondidas? Cuenta qué encontraste o bebe 3'),
    Tile(id: 912, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿A quién de aquí crees que sería el ex más tóxico? Señálalo o bebe 3'),
    Tile(id: 913, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta lo más humillante que hiciste por alguien que te gustaba, o bebe 3'),
    Tile(id: 914, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has vuelto con alguien solo por no estar solo? Cuenta o bebe 3'),
    Tile(id: 924, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿A cuántos ex has stalkeado esta semana? Número real o bebe 3'),
    Tile(id: 925, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Cuál de tus ex ha mejorado más desde que lo dejasteis? Di el nombre o bebe 3'),
    Tile(id: 926, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta lo más patético que hiciste para intentar recuperar a alguien, o bebe 3'),
    Tile(id: 927, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has escrito un mensaje a un ex y lo has borrado sin enviar? Lee lo que ibas a mandar o bebe 3'),
    Tile(id: 928, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has hecho algo solo para que tu ex lo viera en redes? Cuenta o bebe 3'),
    Tile(id: 929, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has quedado con un ex "para hablar" sabiendo que no era solo para hablar? Cuenta o bebe 3'),
    Tile(id: 930, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Di el nombre del ex con el que peor acabaste o bebe 3'),
    Tile(id: 931, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Qué es lo peor que te han dicho en una ruptura? Cuéntalo o bebe 2'),
    Tile(id: 932, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has esperado que tu ex lo pasara mal después de dejarlo? Sé honesto/a o bebe 3'),
    Tile(id: 933, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta la excusa más ridícula que usaste para terminar con alguien o bebe 3'),
    Tile(id: 934, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has pedido perdón a un ex sin sentirlo de verdad? ¿Para qué? Cuéntalo o bebe 3'),

    // YO NUNCA
    Tile(id: 935, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he borrado conversaciones para que mi pareja no las viera. El que sí, bebe'),
    Tile(id: 936, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he dado like a fotos antiguas de alguien para que se diera cuenta. El que sí, bebe'),
    Tile(id: 937, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he seguido viendo a alguien sabiendo que no tenía futuro. El que sí, bebe'),
    Tile(id: 938, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Yo nunca he visto las stories de mi ex desde una cuenta falsa. El que sí, bebe'),
    Tile(id: 939, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he terminado con alguien por WhatsApp. El que sí, bebe'),
    Tile(id: 940, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he usado el "necesito tiempo" para no dar una explicación real. El que sí, bebe'),
    Tile(id: 941, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Yo nunca he hablado mal de mi ex con sus propios amigos. El que sí, bebe'),
    Tile(id: 942, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he comparado a mi pareja con un ex en voz alta. El que sí, bebe'),
    Tile(id: 943, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he seguido a la nueva pareja de mi ex en redes para ver cómo es. El que sí, bebe'),
    Tile(id: 944, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he dejado en visto a alguien aposta para hacerle sufrir. El que sí, bebe'),
    Tile(id: 945, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Yo nunca he vuelto con alguien solo porque la nueva relación me daba más miedo. El que sí, bebe'),

    // CAOS
    Tile(id: 915, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Elige a alguien. Durante un turno sois ex tóxicos y discutís'),
    Tile(id: 916, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Todos dicen una red flag en 5 segundos. El que se quede en blanco, bebe'),
    Tile(id: 946, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'El jugador a tu izquierda te manda un audio de voz de 10 segundos como si fuera tu ex tóxico ahora mismo'),
    Tile(id: 947, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Todos escriben el nombre de su ex más tóxico en el móvil. El que no quiera, bebe 3'),
    Tile(id: 948, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'El grupo elige quién tiene el historial de relaciones más desastroso. Esa persona cuenta su peor historia o bebe 4'),
    Tile(id: 949, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Todos en voz alta: ¿en tu última relación eras más tóxico/a tú o la otra persona? El grupo vota quién miente'),
  ];

  static const List<Tile> broncolaPlus = [
    // SPICY
    Tile(id: 3001, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿En qué trabajo has robado más material de oficina? Cuenta o bebe 2'),
    Tile(id: 3002, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Confiesa el favoritismo más flagrante que hayas visto o hecho en un trabajo, o bebe 2'),
    Tile(id: 3003, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿Cuánto dinero tienes ahora mismo en la cuenta? Dilo o bebe 2 por cada millar que te calles'),
    Tile(id: 3004, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿Qué compra más cara has hecho sin decírselo a nadie? Cuenta o bebe 2'),
    Tile(id: 3005, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Confiesa el mayor engaño en tu currículum o bebe 2'),
    Tile(id: 3006, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿Alguna vez has pedido dinero prestado sin intención de devolverlo pronto? Cuenta o bebe 2'),
    Tile(id: 3007, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Di cuánto cobras al mes. Exacto o bebes 1 por cada 100€ de diferencia'),
    Tile(id: 3008, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿Cuál ha sido tu peor jefe? Cuenta por qué o bebe 2'),
    Tile(id: 3009, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Cuenta la excusa más creativa que hayas usado para no ir a trabajar o bebe 2'),
    Tile(id: 3010, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿Alguna vez has hecho algo en el trabajo del que te podrían haber despedido? Cuenta o bebe 2'),
    Tile(id: 3011, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿Qué app usas más en horario laboral sin que sea de trabajo? Confiesa o bebe 2'),
    Tile(id: 3012, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: '¿Has fingido estar enfermo para librarte de algo que no era trabajo? ¿De qué? Cuenta o bebe 2'),

    // WILD
    Tile(id: 3013, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Di cuánto dinero crees que tiene el jugador más rico de esta mesa. Si te equivocas en más de 500€, bebes 3'),
    Tile(id: 3014, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Qué harías si mañana te ingresaran 50.000€ en la cuenta? Sin filtros o bebe 3'),
    Tile(id: 3015, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Cuál es la compra más estúpida que has hecho en un momento de debilidad? Cuenta o bebe 3'),
    Tile(id: 3016, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿A quién de aquí pedirías dinero prestado primero? Señálalo o bebe 3'),
    Tile(id: 3017, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Confiesa la peor decisión económica de tu vida o bebe 4'),
    Tile(id: 3018, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Has hecho algo deshonesto para conseguir dinero o un trabajo? Di la verdad o bebe 4'),
    Tile(id: 3019, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Cuál sería tu precio para hacer algo que normalmente nunca harías? Propón un número o bebe 3'),
    Tile(id: 3020, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Di quién de aquí crees que más dinero ha gastado esta semana. El grupo vota si aciertas'),
    Tile(id: 3021, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Has pedido un aumento sabiendo que no lo merecías? Cuenta cómo lo justificaste o bebe 3'),
    Tile(id: 3022, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Cuánto cobras? Si no lo dices, bebes 1 trago por cada 200€ que te calles'),
    Tile(id: 3023, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Cuenta el mayor favor que has hecho por dinero o bebe 4'),
    Tile(id: 3024, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Qué harías por 1.000€ ahora mismo que no haría nadie aquí? Proponlo o bebe 3'),
    Tile(id: 3025, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Di cuánto llevas gastado en ocio este mes. Si supera los 200€, bebes 2 extra'),
    Tile(id: 3026, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Alguna vez has mentido en algún trámite oficial o declaración? Cuenta o bebe 3'),
    Tile(id: 3027, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Cuál es el trabajo que harías aunque no te pagaran? ¿Y el que no harías ni por 10.000€? O bebe 2'),
    Tile(id: 3028, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Confiesa la mayor trampa que has hecho en un examen o trabajo académico, o bebe 3'),
    Tile(id: 3029, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Cuánto tiempo llevas sin mirar tu saldo? Quien menos tiempo lleva reparte 3 tragos'),
    Tile(id: 3030, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Di cuál sería tu límite moral para ganar dinero o bebe 4'),
    Tile(id: 3031, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'El grupo decide quién de aquí ganaría más dinero en 10 años. Esa persona reparte 3'),
    Tile(id: 3032, type: TileType.social, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: '¿Cuándo ganaste más dinero en menos tiempo y cómo lo gastaste? Cuenta o bebe 3'),

    // YO NUNCA
    Tile(id: 3033, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he llegado tarde al trabajo más de 3 veces en un mes. El que sí, bebe'),
    Tile(id: 3034, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he dicho que sabía hacer algo en una entrevista sin saber hacerlo. El que sí, bebe'),
    Tile(id: 3035, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he robado algo pequeño en el trabajo. El que sí, bebe'),
    Tile(id: 3036, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he gastado más de lo que tenía en la cuenta. El que sí, bebe'),
    Tile(id: 3037, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he comprado algo solo porque lo tenía otra persona. El que sí, bebe'),
    Tile(id: 3038, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he pedido dinero prestado sin devolverlo. El que sí, bebe'),
    Tile(id: 3039, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he trabajado en negro. El que sí, bebe'),
    Tile(id: 3040, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he mentido en algún trámite económico oficial. El que sí, bebe'),
    Tile(id: 3041, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he cobrado más de 2.500€ al mes. El que haya cobrado más, bebe'),
    Tile(id: 3042, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he rechazado un trabajo por pereza. El que sí, bebe'),
    Tile(id: 3043, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Yo nunca he enviado un CV con datos inventados. El que sí, bebe'),

    // CAOS
    Tile(id: 3044, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'El grupo decide quién pagaría la cuenta si estuvierais en un restaurante. Esa persona bebe 3'),
    Tile(id: 3045, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'Todos dicen su mayor gasto del mes en 5 segundos. El mayor gasto reparte 4 tragos'),
    Tile(id: 3046, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.broncolaPlus,
        text: 'El jugador con menos tragos recibe una propuesta laboral absurda del de su izquierda y decide si acepta'),
    Tile(id: 3047, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Todos votan quién de aquí sobreviviría mejor con 500€ al mes. El perdedor bebe 3'),
    Tile(id: 3048, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'Elige a alguien. Ese jugador tiene que convencer al grupo de invertir en el negocio más absurdo posible'),
    Tile(id: 3049, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.broncolaPlus,
        text: 'El grupo subasta imaginariamente al jugador a tu derecha. El que dé el precio más alto reparte 3'),
  ];

  static const List<Tile> verguenzaAjena = [
    // SPICY
    Tile(id: 3050, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál ha sido tu momento más cringe con alguien que te gustaba? Cuenta o bebe 2'),
    Tile(id: 3051, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Cuenta la situación más bochornosa que hayas vivido en público o bebe 2'),
    Tile(id: 3052, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: '¿Alguna vez te han pillado haciendo algo que no querías que vieran? ¿Qué era? Cuenta o bebe 2'),
    Tile(id: 3053, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Confiesa el texto más cringe que hayas enviado intentando ligar, o bebe 2'),
    Tile(id: 3054, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es el error más ridículo que has cometido delante de tu jefe o profesor? Cuenta o bebe 2'),
    Tile(id: 3055, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: '¿Alguna vez te has caído en público y has fingido que no ha pasado nada? Describe la situación o bebe 2'),
    Tile(id: 3056, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Cuenta la mentira más absurda que hayas dicho para quedar bien y que se te fue de las manos, o bebe 2'),
    Tile(id: 3057, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es la foto o vídeo tuyo que más vergüenza te daría que vieran? Descríbelo o bebe 2'),
    Tile(id: 3058, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Confiesa el momento más incómodo que hayas vivido en casa de alguien o bebe 2'),
    Tile(id: 3059, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: '¿Has confundido a alguien con otra persona y ha sido muy incómodo? Cuenta o bebe 2'),
    Tile(id: 3060, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es la autocorrección más comprometida que te ha jugado una mala pasada? Muéstrala o bebe 2'),
    Tile(id: 3061, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Cuenta alguna vez que hayas dado las gracias a alguien y te haya respondido algo inapropiado, o bebe 2'),

    // WILD
    Tile(id: 3062, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es el momento en el que más has querido que te tragara la tierra? Cuenta o bebe 3'),
    Tile(id: 3063, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'Confiesa la obsesión más cringe que has tenido con algún famoso o bebe 3'),
    Tile(id: 3064, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Alguna vez has llorado en público en un lugar inapropiado? ¿Dónde? Cuenta o bebe 3'),
    Tile(id: 3065, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Tienes algo en tu habitación que te daría vergüenza que encontraran? Descríbelo o bebe 4'),
    Tile(id: 3066, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'Cuenta el momento más vergonzoso que recuerdas de tu etapa adolescente o bebe 3'),
    Tile(id: 3067, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es la búsqueda más vergonzosa que podrías tener en el historial? Dila o bebe 4'),
    Tile(id: 3068, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Alguna vez has fingido no conocer a alguien para evitar saludarle? ¿A quién? Cuenta o bebe 3'),
    Tile(id: 3069, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'Imita el peor momento bochornoso que hayas vivido para que el grupo lo reviva contigo, o bebe 3'),
    Tile(id: 3070, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es la canción más cringe que tienes en tu playlist y que nadie sabe? Dila o bebe 3'),
    Tile(id: 3071, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Has tenido alguna fase estética o de personalidad de la que ahora te arrepientes? Describe cómo eras o bebe 3'),
    Tile(id: 3072, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'Cuenta el último momento en el que has sentido vergüenza ajena por alguien de esta mesa, o bebe 3'),
    Tile(id: 3073, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es tu mayor secreto vergonzoso que nunca le contarías a tu familia? Cuenta o bebe 4'),
    Tile(id: 3074, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Alguna vez has bailado o cantado creyendo que estabas solo y te han pillado? Cuenta o bebe 3'),
    Tile(id: 3075, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es la cosa más patética que has hecho para evitar una conversación incómoda? Cuenta o bebe 3'),
    Tile(id: 3076, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Tienes alguna playlist, cuenta de red social o afición que mantengas en secreto? Confiesa o bebe 3'),
    Tile(id: 3077, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es el comentario más inapropiado que has hecho sin darte cuenta en el momento? Cuenta o bebe 3'),
    Tile(id: 3078, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Alguna vez has fingido saber de qué hablaban y luego has quedado en evidencia? Cuenta o bebe 3'),
    Tile(id: 3079, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'Di el momento más vergonzoso que has tenido en una primera cita o bebe 4'),
    Tile(id: 3080, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Cuál es la cosa más ridícula que has comprado online a las 3 de la mañana? Cuenta o bebe 3'),
    Tile(id: 3081, type: TileType.social, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: '¿Alguna vez has dicho mal una palabra durante años sin que nadie te corrigiera? ¿Cuál? Cuenta o bebe 3'),

    // YO NUNCA
    Tile(id: 3082, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he enviado un mensaje al grupo equivocado. El que sí, bebe'),
    Tile(id: 3083, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca me he dado cuenta tarde de que llevaba algo mal puesto todo el día. El que sí, bebe'),
    Tile(id: 3084, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he saludado a alguien que no me saludaba y he fingido que era a otro. El que sí, bebe'),
    Tile(id: 3085, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he reído una gracia sin haberla entendido para no quedar mal. El que sí, bebe'),
    Tile(id: 3086, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he tropezado o caído en público y he seguido como si nada. El que sí, bebe'),
    Tile(id: 3087, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he hecho un comentario incómodo en un silencio que no había que llenar. El que sí, bebe'),
    Tile(id: 3088, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca me he dado cuenta de que llevaba comida en los dientes después de una conversación larga. El que sí, bebe'),
    Tile(id: 3089, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he pronunciado mal el nombre de alguien varias veces antes de que me corrigieran. El que sí, bebe'),
    Tile(id: 3090, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he aplaudido cuando nadie aplaudía o viceversa. El que sí, bebe'),
    Tile(id: 3091, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca he tenido un fan account de algún famoso. El que sí, bebe'),
    Tile(id: 3092, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Yo nunca me he inventado haber visto una película o leído un libro para quedar bien. El que sí, bebe'),

    // CAOS
    Tile(id: 3093, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Todos cuentan su mayor fail de redes sociales en 10 segundos. El más cringe reparte 4 tragos'),
    Tile(id: 3094, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'El jugador a tu izquierda tiene que leer en voz alta su publicación de redes más vergonzosa que encuentre'),
    Tile(id: 3095, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'El grupo elige quién de aquí tendría la fase emo más intensa de adolescente. Esa persona bebe 3'),
    Tile(id: 3096, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.verguenzaAjena,
        text: 'Todos imitan al jugador a su derecha haciendo algo ridículo durante 10 segundos'),
    Tile(id: 3097, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'El grupo vota quién tiene la foto de perfil más cringe de su historial. El ganador bebe 4'),
    Tile(id: 3098, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.verguenzaAjena,
        text: 'Todos confiesan en voz alta la última búsqueda que han hecho en Google. El más vergonzoso reparte 3'),
  ];

  static const List<Tile> caosTotal = [
    // SPICY
    Tile(id: 3099, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Qué norma social romperías si pudieras hacerlo sin consecuencias? Cuenta o bebe 2'),
    Tile(id: 3100, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Qué es lo más impulsivo que has hecho en los últimos 6 meses? Cuenta o bebe 2'),
    Tile(id: 3101, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Cuál es la decisión más caótica que has tomado y que salió bien? Cuenta o bebe 2'),
    Tile(id: 3102, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Describe el plan más irresponsable al que hayas dicho que sí sin pensarlo, o bebe 2'),
    Tile(id: 3103, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Cuál es el mayor riesgo calculado que has tomado? ¿Mereció la pena? Cuenta o bebe 2'),
    Tile(id: 3104, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Alguna vez has hecho algo solo porque te dijeron que no podías? Cuenta o bebe 2'),
    Tile(id: 3105, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Qué es lo más espontáneo que has hecho en el último año? Cuenta o bebe 2'),
    Tile(id: 3106, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Cuál es el plan más absurdo que has propuesto y al que alguien dijo que sí? Cuenta o bebe 2'),
    Tile(id: 3107, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Qué cosa fuera de tu zona de confort has hecho por presión del grupo? Cuenta o bebe 2'),
    Tile(id: 3108, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Cuenta la cadena de mala suerte más larga que hayas tenido en un solo día, o bebe 2'),
    Tile(id: 3109, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Cuál es la situación más caótica en la que te has visto metido sin querer? Cuenta o bebe 2'),
    Tile(id: 3110, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: '¿Has tomado alguna decisión importante lanzando una moneda o dejándolo al azar? Cuenta o bebe 2'),

    // WILD
    Tile(id: 3111, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'El grupo decide el reto más ridículo que debes hacer ahora mismo o bebes 5'),
    Tile(id: 3112, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuál sería tu primer movimiento si mañana todo fuera legal durante 24 horas? Sin filtros o bebe 4'),
    Tile(id: 3113, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Qué es lo más caótico que harías si supieras que no te van a pillar nunca? Cuenta o bebe 3'),
    Tile(id: 3114, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Di quién de aquí crees que es un agente del caos disfrazado de persona normal, o bebe 3'),
    Tile(id: 3115, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuántas veces has ignorado una señal de alarma y ha acabado exactamente como pensabas? Cuenta o bebe 3'),
    Tile(id: 3116, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Cuenta la situación más incontrolable en la que hayas estado y cómo saliste de ella, o bebe 3'),
    Tile(id: 3117, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Qué cosa completamente irracional harías si hoy te importara cero el qué dirán? Cuenta o bebe 3'),
    Tile(id: 3118, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuál es el plan más salvaje al que has dicho que sí esta semana o este mes? Cuenta o bebe 3'),
    Tile(id: 3119, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Propón un reto absurdo para el grupo. Si nadie acepta, bebes 4'),
    Tile(id: 3120, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuál es la norma de esta partida que eliminarías si pudieras? Dila o bebe 3'),
    Tile(id: 3121, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Cuenta la vez que más has actuado por impulso puro y qué pasó después, o bebe 3'),
    Tile(id: 3122, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuál es la promesa más imposible que has cumplido? O la más imposible que has roto. Cuenta o bebe 3'),
    Tile(id: 3123, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Di qué harías si esta noche se fuera la luz en mitad de la partida y no volvieras a casa, o bebe 3'),
    Tile(id: 3124, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Alguna vez has saboteado un plan propio o ajeno adrede? Cuenta por qué o bebe 4'),
    Tile(id: 3125, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuál es el peor consejo que has seguido al pie de la letra? ¿Qué pasó? Cuenta o bebe 3'),
    Tile(id: 3126, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'El grupo diseña la situación más caótica posible. El jugador elige si bebe 5 o la describe'),
    Tile(id: 3127, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Qué cosa haría estallar el caos en esta mesa ahora mismo? Dila o bebe 3'),
    Tile(id: 3128, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuándo fue la última vez que actuaste sin pensar en las consecuencias? Cuenta o bebe 4'),
    Tile(id: 3129, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Di quién de aquí montaría el mejor caos en un lugar público. Si el grupo coincide, esa persona bebe 3'),
    Tile(id: 3130, type: TileType.social, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: '¿Cuál es tu plan de emergencia si todo se va a pique mañana? Cuenta o bebe 3'),

    // YO NUNCA
    Tile(id: 3131, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he hecho algo solo porque me retaron. El que sí, bebe'),
    Tile(id: 3132, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he provocado caos accidentalmente y he fingido que no fui yo. El que sí, bebe'),
    Tile(id: 3133, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he empezado algo que no pude parar. El que sí, bebe'),
    Tile(id: 3134, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he dicho "¿a que no te atreves?" y me ha salido mal. El que sí, bebe'),
    Tile(id: 3135, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he llegado tarde a algo importante por quedarme dormido. El que sí, bebe'),
    Tile(id: 3136, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he perdido algo importante por dejarlo al azar. El que sí, bebe'),
    Tile(id: 3137, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he salido a la calle sin dinero ni llaves y me ha dado igual. El que sí, bebe'),
    Tile(id: 3138, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Yo nunca he tomado una decisión importante con los ojos cerrados. El que sí, bebe'),
    Tile(id: 3139, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Yo nunca he organizado un plan que se convirtió en un desastre total. El que sí, bebe'),
    Tile(id: 3140, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he roto algo ajeno y lo he vuelto a poner como si nada. El que sí, bebe'),
    Tile(id: 3141, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.caosTotal,
        text: 'Yo nunca he mentido para entrar en un sitio. El que sí, bebe'),

    // CAOS
    Tile(id: 3142, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'El grupo vota la decisión más caótica que se podría tomar ahora mismo. La mayoría decide'),
    Tile(id: 3143, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Todos proponen un reto para el jugador de su izquierda en 10 segundos. El más votado se ejecuta o ese jugador bebe 4'),
    Tile(id: 3144, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'El jugador con más tragos decide una regla nueva que dure 3 rondas'),
    Tile(id: 3145, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Elige a alguien. Ese jugador tiene que hacer exactamente lo contrario de lo que le digan durante un minuto'),
    Tile(id: 3146, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'El grupo vota quién sería el mejor líder en una situación de caos absoluto. Esa persona reparte 5 tragos'),
    Tile(id: 3147, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.caosTotal,
        text: 'Todos dicen el reto más descabellado que harían esta noche. El grupo vota el mejor; quien lo propuso bebe 3 si no se atreve'),
  ];

  // Pack privado — solo se compila con: flutter build --dart-define=PRIVATE_PACK=true
  static const List<Tile> amigos = bool.fromEnvironment('PRIVATE_PACK')
      ? [
          // ── QUÉ PREFIERES ──────────────────────────────────────────────
          Tile(id: 950, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: tener penes en lugar de dedos o vaginas en las palmas de las manos?"),
          Tile(id: 951, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: un buen sexo oral de tu abuela/o que dure poco o un mal sexo oral de tu abuela/o que dure mucho?"),
          Tile(id: 952, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a tu madre/padre en el cuerpo de tu pareja o al revés?"),
          Tile(id: 953, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: el juego del hobbit o al tío Juan Carlos?"),
          Tile(id: 954, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: tener un orgasmo sonoro cada vez que estornudes o cagarte encima cada vez que toses?"),
          Tile(id: 955, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a Josito o no?"),
          Tile(id: 956, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: no volver a salir de tu casa nunca más o ser un vagabundo de la Azohía?"),
          Tile(id: 957, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: que las manos te huelan como pies sudados o que el aliento te huela a pozo negro?"),
          Tile(id: 958, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: ser zoofílico o necrófilo?"),
          Tile(id: 959, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: una patada en los cojones o dos?"),
          Tile(id: 960, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: correrte en 5 segundos o tardar 3 horas?"),
          Tile(id: 961, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a un furro o a un therian?"),
          Tile(id: 962, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: mandar una foto íntima al grupo familiar o que te la envíe a ti tu madre?"),
          Tile(id: 963, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: una paja ajena o mamada propia?"),
          Tile(id: 964, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: ser Spiderman o Miguel Carcaño?"),
          Tile(id: 965, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Qué prefieres: borrar tu peor recuerdo o volver a vivir el mejor?"),
          Tile(id: 966, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a la Falete o a la Marrash?"),
          Tile(id: 967, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: casarte con Dalas o con Jpelirrojo?"),
          Tile(id: 968, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: salir con el Xokas o con Rickyedit?"),
          Tile(id: 969, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Qué prefieres: sopa de murciélago o sopa de cobaya?"),
          Tile(id: 970, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: 5000€ al mes pero comer mierda una vez al mes, o 3000€ al mes por beber un poco de pis una vez a la semana?"),
          Tile(id: 971, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: ser acosado sexualmente en el trabajo o ser acosado laboralmente en el sexo?"),
          Tile(id: 972, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: quedarte embarazado/a con un beso o embarazar a alguien con un beso?"),

          // ── YO NUNCA ────────────────────────────────────────────────────
          Tile(id: 973, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he cagado encima. El que sí, bebe."),
          Tile(id: 974, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he sentido atraído/a por el padre o la madre de un amigo/a. El que sí, bebe."),
          Tile(id: 975, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho un trío con un chino y un inglés (qué específico). El que sí, bebe."),
          Tile(id: 976, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he follado a Josito. El que sí, bebe."),
          Tile(id: 977, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he salido o me he follado a alguien por compromiso. El que sí, bebe."),
          Tile(id: 978, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca le he cagado la polla a alguien. El que sí, bebe."),
          Tile(id: 979, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me liaría con Danny DeVito. El que sí, bebe."),
          Tile(id: 980, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he lamido un sobaco ajeno... o propio. El que sí, bebe."),
          Tile(id: 981, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he lamido pies. El que sí, bebe."),
          Tile(id: 982, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he pensado en otra persona mientras follaba. El que sí, bebe."),
          Tile(id: 983, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he mentido sobre hacer trampas en un juego. El que sí, bebe."),
          Tile(id: 984, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho una paja con los pies. El que sí, bebe."),
          Tile(id: 985, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he fingido un orgasmo. El que sí, bebe."),
          Tile(id: 986, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he meado en una piscina ajena. El que sí, bebe."),
          Tile(id: 987, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he hecho una cuenta falsa para stalkear a alguien. El que sí, bebe."),
          Tile(id: 988, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he follado con la regla. El que sí, bebe."),
          Tile(id: 989, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he disfrazado para hacer el acto sexual. El que sí, bebe."),
          Tile(id: 990, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho una paja en un lugar público. El que sí, bebe."),
          Tile(id: 991, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he follado en la cama de la abuela. El que sí, bebe."),
          Tile(id: 992, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he follado en casa ajena. El que sí, bebe."),
          Tile(id: 993, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he follado y me he arrepentido al terminar. El que sí, bebe."),
          Tile(id: 994, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he dicho que iba a acabar bien con mi ex y luego ha ido como la mierda. El que sí, bebe."),
          Tile(id: 995, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he tenido sexo anal y ha salido hecha un mikado. El que sí, bebe."),
          Tile(id: 996, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he metido fruta o verdura por el culo. El que sí, bebe."),
          Tile(id: 997, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he estado enamorado/a de verdad. El que sí, bebe."),
          Tile(id: 998, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he masturbado después de follar por no quedar satisfecho/a. El que sí, bebe."),
          Tile(id: 1000, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he querido a dos personas a la vez. El que sí, bebe."),
          Tile(id: 1001, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho un Simba. El que sí, bebe."),
          Tile(id: 1002, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he criticado a un amigo/a con otro amigo/a del mismo grupo. El que sí, bebe."),
          Tile(id: 1003, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he robado ropa interior. El que sí, bebe."),
          Tile(id: 1004, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he ido a una orgía. El que sí, bebe."),
          Tile(id: 1005, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he lamido un pene o chochito que olía a cadáver. El que sí, bebe."),
          Tile(id: 1006, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho cruising. El que sí, bebe."),
          Tile(id: 1007, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he ido a una sauna gay. El que sí, bebe."),
          Tile(id: 1008, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he tomado una castaña más mala que la mierda en el Pedrotito. El que sí, bebe."),
          Tile(id: 1009, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he tonteado con alguien sabiendo que tenía pareja. El que sí, bebe."),
          Tile(id: 1010, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he liado con un amigo/a. El que sí, bebe."),
          Tile(id: 1011, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he zorreado con alguien para darle celos a otra persona. El que sí, bebe."),
          Tile(id: 1012, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he robado algo de más de 10 euros. El que sí, bebe."),

          // ── QUIÉN ES MÁS PROBABLE ───────────────────────────────────────
          Tile(id: 1013, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que mame pito esta noche? El grupo señala. El más señalado bebe."),
          Tile(id: 1014, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que NO mame pito esta noche? El grupo señala. El más señalado bebe."),
          Tile(id: 1015, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que salga en un vídeo de Trakatá? El grupo señala. El más señalado bebe."),
          Tile(id: 1016, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que ponga una excusa para no venir a un plan? El grupo señala. El más señalado bebe."),
          Tile(id: 1017, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se pique por una tontería? El grupo señala. El más señalado bebe."),
          Tile(id: 1018, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se folle a Josito? El grupo señala. El más señalado bebe."),
          Tile(id: 1019, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que golpee un perro? El grupo señala. El más señalado bebe."),
          Tile(id: 1020, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que patee un gato? El grupo señala. El más señalado bebe."),
          Tile(id: 1021, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que abofetee un hámster? El grupo señala. El más señalado bebe."),
          Tile(id: 1022, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que mate un canguro? El grupo señala. El más señalado bebe."),
          Tile(id: 1023, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se lleve un arroz con voces? El grupo señala. El más señalado bebe."),
          Tile(id: 1024, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que acabe en una trieja? El grupo señala. El más señalado bebe."),
          Tile(id: 1025, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se vuelva viral en redes? El grupo señala. El más señalado bebe."),
          Tile(id: 1026, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que dé más vergüenza estando borracho/a? El grupo señala. El más señalado bebe."),
          Tile(id: 1027, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se grabe follando? El grupo señala. El más señalado bebe."),
          Tile(id: 1028, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que le revise el móvil a su pareja? El grupo señala. El más señalado bebe."),
          Tile(id: 1029, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que salga con la expareja de un amigo/a? El grupo señala. El más señalado bebe."),
          Tile(id: 1030, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que tenga una relación abierta en Madrid? El grupo señala. El más señalado bebe."),
          Tile(id: 1031, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a Skin y se le corran en la espalda? El grupo señala. El más señalado bebe."),
          Tile(id: 1032, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a la casa de los gemelos? El grupo señala. El más señalado bebe."),
          Tile(id: 1033, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se cambie de acera? El grupo señala. El más señalado bebe."),
          Tile(id: 1034, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a la isla de las tentaciones? El grupo señala. El más señalado bebe."),
          Tile(id: 1035, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que acabe haciendo cruising donde el Tracatrá? El grupo señala. El más señalado bebe."),
          Tile(id: 1036, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a una sauna gay? El grupo señala. El más señalado bebe."),
          Tile(id: 1037, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que venda fotos de los pies? El grupo señala. El más señalado bebe."),
          Tile(id: 1038, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que no responda al WhatsApp? El grupo señala. El más señalado bebe."),
          Tile(id: 1039, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se quede dormido/a antes de un evento importante? El grupo señala. El más señalado bebe."),
          Tile(id: 1040, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se case primero? El grupo señala. El más señalado bebe."),
          Tile(id: 1041, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se abra un OnlyFans? El grupo señala. El más señalado bebe."),
          Tile(id: 1042, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que sea infiel? El grupo señala. El más señalado bebe."),
          Tile(id: 1043, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que acabe en una secta? El grupo señala. El más señalado bebe."),
          Tile(id: 1044, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya al espacio? El grupo señala. El más señalado bebe."),
          Tile(id: 1045, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se meta a monja o cura? El grupo señala. El más señalado bebe."),
          Tile(id: 1046, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que sea captado por una secta? El grupo señala. El más señalado bebe."),
        ]
      : [];

  // ── Tiles base modo Extremo: contenido apto para app pública ─────────────
  // Estas cartas forman parte del pool del juego base (wild) y no requieren
  // ningún pack adicional. Se mezclan con TileCatalog.wild automáticamente
  // a través de _basePoolFor en BoardBuilder / DeckBuilder.
  static const List<Tile> wildExtra = [
    // ── ¿QUÉ PREFIERES? ──────────────────────────────────────────────────────
    Tile(id: 2001, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: tener un orgasmo sonoro cada vez que estornudes o cagarte encima cada vez que toses?'),
    Tile(id: 2002, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: no volver a salir de tu casa nunca más o ser un vagabundo?'),
    Tile(id: 2003, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: que las manos te huelan siempre mal o que el aliento sea insoportable?'),
    Tile(id: 2004, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: una patada en los cojones o dos?'),
    Tile(id: 2005, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: correrte en 5 segundos o tardar 3 horas?'),
    Tile(id: 2006, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: borrar tu peor recuerdo o volver a vivir el mejor?'),
    Tile(id: 2007, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: sopa rarísima o comida aún más rara?'),
    Tile(id: 2008, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: 5000€ al mes pero comer algo asqueroso una vez al mes, o 3000€ al mes por beber algo raro cada semana?'),
    Tile(id: 2009, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: quedarte embarazado/a con un beso o embarazar a alguien con un beso?'),
    Tile(id: 2049, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: que todos puedan leer tus pensamientos o que tú puedas leer los de todos?'),
    Tile(id: 2050, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: que cada vez que mintas te salga humo por las orejas o que cada vez que te guste alguien lo digas en voz alta sin poder evitarlo?'),
    Tile(id: 2051, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: que tu ex sepa todo lo que has pensado de él/ella o que tus padres lean tus últimos 100 mensajes?'),
    Tile(id: 2052, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: no poder usar el móvil nunca más o no poder salir de casa sin que alguien te acompañe?'),
    Tile(id: 2053, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: envejecer físicamente al triple de velocidad o mentalmente al triple?'),
    Tile(id: 2054, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: ser invisible pero sin poder apagarlo o volar pero solo a 10 cm del suelo?'),
    Tile(id: 2055, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: perder todos tus recuerdos de los últimos 5 años o no poder crear recuerdos nuevos durante 1 año?'),
    Tile(id: 2056, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: que publiquen tu historial de búsqueda del último mes o que graben lo que haces mientras duermes una semana y lo vea todo el mundo?'),
    Tile(id: 2057, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: tener siempre demasiado calor o siempre demasiado frío?'),
    Tile(id: 2058, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: descubrir que tu mejor amigo/a te ha mentido sobre algo importante o que tu pareja lleva años guardando un secreto?'),
    Tile(id: 2059, type: TileType.social, mode: GameMode.wild,
        text: '¿Qué prefieres: no poder hablar en voz alta nunca más o no poder susurrar nunca más?'),

    // ── YO NUNCA ─────────────────────────────────────────────────────────────
    Tile(id: 2010, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca me he cagado encima. El que sí, bebe.'),
    Tile(id: 2011, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he salido o estado con alguien por compromiso. El que sí, bebe.'),
    Tile(id: 2012, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he lamido un sobaco. El que sí, bebe.'),
    Tile(id: 2013, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he lamido pies. El que sí, bebe.'),
    Tile(id: 2014, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he pensado en otra persona mientras estaba con alguien. El que sí, bebe.'),
    Tile(id: 2015, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he mentido sobre hacer trampas en un juego. El que sí, bebe.'),
    Tile(id: 2016, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he fingido un orgasmo. El que sí, bebe.'),
    Tile(id: 2017, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he meado en una piscina. El que sí, bebe.'),
    Tile(id: 2018, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca me he hecho una cuenta falsa para stalkear. El que sí, bebe.'),
    Tile(id: 2019, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca me he disfrazado para una situación íntima. El que sí, bebe.'),
    Tile(id: 2020, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he hecho algo íntimo en un lugar público. El que sí, bebe.'),
    Tile(id: 2021, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he estado con alguien en casa ajena. El que sí, bebe.'),
    Tile(id: 2022, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca me he arrepentido después de liarme o acostarme con alguien. El que sí, bebe.'),
    Tile(id: 2023, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca me he quedado con ganas después de un encuentro. El que sí, bebe.'),
    Tile(id: 2024, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he querido a dos personas a la vez. El que sí, bebe.'),
    Tile(id: 2025, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he criticado a un amigo con otro del grupo. El que sí, bebe.'),
    Tile(id: 2026, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he tonteado con alguien sabiendo que tenía pareja. El que sí, bebe.'),
    Tile(id: 2027, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca me he liado con un amigo/a. El que sí, bebe.'),
    Tile(id: 2028, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he provocado celos aposta. El que sí, bebe.'),
    Tile(id: 2029, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.neverHaveIEver,
        text: 'Yo nunca he robado algo. El que sí, bebe.'),

    // ── ¿QUIÉN ES MÁS PROBABLE? ──────────────────────────────────────────────
    Tile(id: 2030, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que ponga una excusa para no venir a un plan? El grupo señala. El más señalado bebe.'),
    Tile(id: 2031, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que se pique por una tontería? El grupo señala. El más señalado bebe.'),
    Tile(id: 2032, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que se lleve un arroz con voces? El grupo señala. El más señalado bebe.'),
    Tile(id: 2033, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que acabe en una relación complicada? El grupo señala. El más señalado bebe.'),
    Tile(id: 2034, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que se vuelva viral? El grupo señala. El más señalado bebe.'),
    Tile(id: 2035, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que dé más vergüenza borracho/a? El grupo señala. El más señalado bebe.'),
    Tile(id: 2036, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que revise el móvil de su pareja? El grupo señala. El más señalado bebe.'),
    Tile(id: 2037, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que salga con la ex de un amigo? El grupo señala. El más señalado bebe.'),
    Tile(id: 2038, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que tenga una relación abierta? El grupo señala. El más señalado bebe.'),
    Tile(id: 2039, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que vaya a la isla de las tentaciones? El grupo señala. El más señalado bebe.'),
    Tile(id: 2040, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que venda fotos de los pies? El grupo señala. El más señalado bebe.'),
    Tile(id: 2041, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que no responda al WhatsApp? El grupo señala. El más señalado bebe.'),
    Tile(id: 2042, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que se quede dormido antes de algo importante? El grupo señala. El más señalado bebe.'),
    Tile(id: 2043, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que se case primero? El grupo señala. El más señalado bebe.'),
    Tile(id: 2044, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que se abra un OnlyFans? El grupo señala. El más señalado bebe.'),
    Tile(id: 2045, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que sea infiel? El grupo señala. El más señalado bebe.'),
    Tile(id: 2046, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que acabe en una secta? El grupo señala. El más señalado bebe.'),
    Tile(id: 2047, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que vaya al espacio? El grupo señala. El más señalado bebe.'),
    Tile(id: 2048, type: TileType.groupDrink, mode: GameMode.wild,
        category: TileCategory.whoIsMostLikely,
        text: '¿Quién es más probable que cambie radicalmente de vida? El grupo señala. El más señalado bebe.'),
  ];

  static const Tile finale = Tile(
    id: 999,
    type: TileType.finale,
    text: '¡BRONCOLA FINAL!',
  );
}
