import '../models/content_pack.dart';
import '../models/game_mode.dart';
import '../models/tile.dart';

class TileCatalog {
  static const List<Tile> universal = [
    Tile(id: 101, type: TileType.drink, text: 'Bebe 1 trago'),
    Tile(id: 102, type: TileType.drink, text: 'Bebe 2 tragos'),
    Tile(id: 103, type: TileType.drink, text: 'Bebe 3 tragos'),
    Tile(id: 104, type: TileType.drink, text: 'Bebe 4 tragos'),
    Tile(id: 105, type: TileType.drink, text: 'Bebe tantos tragos como letras tenga tu nombre'),
    Tile(id: 106, type: TileType.drink, text: 'Bebe 2 tragos por cada vocal de tu nombre'),
    Tile(id: 107, type: TileType.groupDrink, text: 'Brindis obligatorio. Beben todos'),
    Tile(id: 108, type: TileType.groupDrink, text: 'Los dos jugadores con menos tragos beben 1'),
    Tile(id: 109, type: TileType.groupDrink, text: 'Los que lleven colores oscuros beben 2'),
    Tile(id: 110, type: TileType.groupDrink, text: 'Beben todos y el que termine último bebe otro'),
    Tile(id: 111, type: TileType.chaos, text: 'Elige quién bebe 4 tragos'),
    Tile(id: 112, type: TileType.chaos, text: 'El último en ponerse de pie bebe 3 tragos'),
    Tile(id: 113, type: TileType.chaos, text: 'Intercambia la bebida con la persona de tu derecha'),
    Tile(id: 114, type: TileType.chaos, text: 'El más serio bebe 2. Lo decide el grupo'),
    Tile(id: 115, type: TileType.chaos, text: 'Reparte 4 tragos como quieras'),
    Tile(id: 116, type: TileType.rule, text: 'Nueva regla'),
    Tile(id: 117, type: TileType.rule, text: 'Nueva regla'),
    Tile(id: 118, type: TileType.rule, text: 'Nueva regla'),
    Tile(id: 119, type: TileType.chaos, text: 'El jugador anterior a ti bebe 3 tragos'),
    Tile(id: 120, type: TileType.chaos, text: 'Reparte 4 tragos como quieras entre los jugadores'),
    Tile(id: 121, type: TileType.special, text: 'Intercambia el número de tragos con otro jugador', specialEffect: SpecialTileEffect.swapWithPlayer),
    Tile(id: 122, type: TileType.special, text: '¡Carta extra! Roba otra carta ahora mismo', specialEffect: SpecialTileEffect.rollAgain),
    Tile(id: 123, type: TileType.special, text: '¡Turno doble! Roba otra carta', specialEffect: SpecialTileEffect.rollAgain),
    Tile(id: 801, type: TileType.wildcard, text: 'Comodín: el grupo inventa un reto ahora mismo'),
    Tile(id: 802, type: TileType.wildcard, text: 'Comodín: el jugador a tu izquierda decide qué haces'),
    Tile(id: 803, type: TileType.wildcard, text: 'Comodín: el grupo vota un reto para ti. Lo que diga la mayoría, va'),
  ];

  static const List<Tile> light = [
    Tile(id: 501, type: TileType.social, mode: GameMode.light, category: TileCategory.truth, text: 'Verdad: cuenta la anécdota más absurda que te haya pasado de fiesta'),
    Tile(id: 502, type: TileType.social, mode: GameMode.light, category: TileCategory.dare, text: 'Reto: habla durante una ronda con voz de locutor o bebe 2'),
    Tile(id: 503, type: TileType.social, mode: GameMode.light, category: TileCategory.neverHaveIEver, text: 'Nunca nunca: el que lo haya hecho bebe 2 tragos'),
    Tile(id: 504, type: TileType.social, mode: GameMode.light, category: TileCategory.actOut, text: 'Imitación: el grupo elige un famoso y tienes que imitarlo'),
    Tile(id: 505, type: TileType.social, mode: GameMode.light, text: 'Di algo bueno de cada jugador o bebe 1 por cada uno que te saltes'),
    Tile(id: 506, type: TileType.social, mode: GameMode.light, text: 'El de tu izquierda te pone un apodo para esta ronda'),
    Tile(id: 507, type: TileType.social, mode: GameMode.light, text: 'Cuenta tu peor chiste. Si nadie se ríe, bebe 2'),
    Tile(id: 508, type: TileType.social, mode: GameMode.light, text: '¿Quién acabaría antes perdiendo el móvil? El grupo decide'),
    Tile(id: 509, type: TileType.social, mode: GameMode.light, text: 'Confiesa un pequeño drama reciente o bebe 3'),
    Tile(id: 510, type: TileType.social, mode: GameMode.light, text: 'Haz una pose ridícula hasta que vuelva tu turno'),
    Tile(id: 511, type: TileType.social, mode: GameMode.light, text: 'La persona de tu derecha te hace una pregunta. Responde o bebe 3'),
    Tile(id: 512, type: TileType.social, mode: GameMode.light, text: 'Todos dicen una manía tuya. Si te enfadas, bebes 2'),
    Tile(id: 513, type: TileType.social, mode: GameMode.light, text: 'Haz reír al grupo. Si fallas, bebe 2'),
    Tile(id: 514, type: TileType.social, mode: GameMode.light, text: 'Di qué superpoder usarías esta noche y por qué, o bebe 2'),
    Tile(id: 515, type: TileType.social, mode: GameMode.light, text: 'La persona más puntual reparte 2 tragos'),
    Tile(id: 516, type: TileType.social, mode: GameMode.light, text: 'Cuenta una anécdota vergonzosa del cole o bebe 3'),
    Tile(id: 517, type: TileType.social, mode: GameMode.light, text: 'Todos señalan al más probable de montar una bronca. Ese bebe 2'),
    Tile(id: 518, type: TileType.social, mode: GameMode.light, text: 'Haz una mini actuación como camarero borde'),
  ];

  static const List<Tile> spicy = [
    Tile(id: 601, type: TileType.social, mode: GameMode.spicy, category: TileCategory.truth, text: 'Verdad: ¿qué mensaje te arrepientes más de haber enviado? Cuéntalo o bebe 3'),
    Tile(id: 602, type: TileType.social, mode: GameMode.spicy, category: TileCategory.dare, text: 'Reto: deja que el grupo elija tu foto de perfil hasta el próximo turno'),
    Tile(id: 603, type: TileType.social, mode: GameMode.spicy, category: TileCategory.neverHaveIEver, text: 'Nunca nunca picante: quien lo haya hecho bebe 3'),
    Tile(id: 604, type: TileType.social, mode: GameMode.spicy, category: TileCategory.actOut, text: 'Actuación: interpreta una cita desastrosa durante 20 segundos'),
    Tile(id: 605, type: TileType.social, mode: GameMode.spicy, text: 'Lee el último emoji que enviaste y explica el contexto o bebe 3'),
    Tile(id: 606, type: TileType.social, mode: GameMode.spicy, text: '¿Quién de aquí tiene más labia? El grupo decide'),
    Tile(id: 607, type: TileType.social, mode: GameMode.spicy, text: 'Confiesa tu peor cita o bebe 4'),
    Tile(id: 608, type: TileType.social, mode: GameMode.spicy, text: 'Todos votan en voz alta quién liga mejor. Esa persona reparte 3'),
    Tile(id: 609, type: TileType.social, mode: GameMode.spicy, text: 'Muestra la última búsqueda vergonzosa o bebe 3'),
    Tile(id: 610, type: TileType.social, mode: GameMode.spicy, text: 'Di quién de aquí te respondería antes a las 3 a.m. o bebe 2'),
    Tile(id: 611, type: TileType.social, mode: GameMode.spicy, text: 'Cuenta la mentira romántica más absurda que hayas dicho o bebe 3'),
    Tile(id: 612, type: TileType.social, mode: GameMode.spicy, text: 'Imita cómo ligarías con alguien del grupo sin decir su nombre, o bebe 3'),
    Tile(id: 613, type: TileType.social, mode: GameMode.spicy, text: 'Confiesa algo que aún te da vergüenza recordar o bebe 4'),
    Tile(id: 614, type: TileType.social, mode: GameMode.spicy, text: 'El grupo elige una app y debes abrir la última notificación recibida o beber 3'),
    Tile(id: 615, type: TileType.social, mode: GameMode.spicy, text: 'Di el nombre de la peor red flag que has ignorado o bebe 2'),
    Tile(id: 616, type: TileType.social, mode: GameMode.spicy, text: 'Haz una escena de celos totalmente exagerada o bebe 3'),
    Tile(id: 617, type: TileType.social, mode: GameMode.spicy, text: 'Todos dicen quién sería peor ex. El más nombrado bebe 2'),
    Tile(id: 618, type: TileType.social, mode: GameMode.spicy, text: 'Cuenta qué persona te ha dejado más en visto o bebe 2'),
  ];

  static const List<Tile> wild = [
    Tile(id: 701, type: TileType.social, mode: GameMode.wild, category: TileCategory.truth, text: 'Verdad extrema: cuenta la mayor locura que has hecho por orgullo, o bebe 4'),
    Tile(id: 702, type: TileType.social, mode: GameMode.wild, category: TileCategory.dare, text: 'Reto extremo: deja que el grupo te redacte un estado absurdo'),
    Tile(id: 703, type: TileType.social, mode: GameMode.wild, category: TileCategory.neverHaveIEver, text: 'Nunca nunca salvaje: quien lo haya hecho bebe 4'),
    Tile(id: 704, type: TileType.social, mode: GameMode.wild, category: TileCategory.actOut, text: 'Interpretación: actúa como villano de telenovela señalando a un traidor'),
    Tile(id: 705, type: TileType.social, mode: GameMode.wild, text: 'Di quién te cae peor en este momento o bebe 5'),
    Tile(id: 706, type: TileType.social, mode: GameMode.wild, text: 'El grupo te hace una pregunta y respondes sin filtro o bebes 5'),
    Tile(id: 707, type: TileType.social, mode: GameMode.wild, text: 'Confiesa la peor mentira que has sostenido demasiado tiempo, o bebe 4'),
    Tile(id: 708, type: TileType.social, mode: GameMode.wild, text: 'Enséñale al grupo la última foto que te dio vergüenza guardar o bebe 5'),
    Tile(id: 709, type: TileType.social, mode: GameMode.wild, text: 'Haz una imitación dramática de alguien famoso en pleno escándalo'),
    Tile(id: 710, type: TileType.social, mode: GameMode.wild, text: 'Todos señalan a quien sería más caótico como compañero de piso. Ese bebe 3'),
    Tile(id: 711, type: TileType.social, mode: GameMode.wild, text: 'Cuenta qué harías con 1000 euros si nadie pudiera juzgarte, o bebe 3'),
    Tile(id: 712, type: TileType.social, mode: GameMode.wild, text: 'Elige entre sinceridad total o beber 6'),
    Tile(id: 713, type: TileType.social, mode: GameMode.wild, text: 'Haz un discurso de ruptura inventado como si estuvieras en una película'),
    Tile(id: 714, type: TileType.social, mode: GameMode.wild, text: 'Di cuál ha sido tu peor impulso esta semana o bebe 3'),
    Tile(id: 715, type: TileType.social, mode: GameMode.wild, text: 'El grupo decide si tu historia es verdad o mentira. Si no te creen, bebes 4'),
    Tile(id: 716, type: TileType.social, mode: GameMode.wild, text: 'Cuenta la cosa más temeraria que harías por una apuesta o bebe 3'),
    Tile(id: 717, type: TileType.social, mode: GameMode.wild, text: 'Nombra a quien crees que se mete antes en un lío. Si coincide el grupo, bebe'),
    Tile(id: 718, type: TileType.social, mode: GameMode.wild, text: 'Actúa como si te hubieran pillado en una mentira gigantesca'),
  ];

  static const List<Tile> exToxico = [
    // SPICY
    Tile(id: 901, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Qué red flag viste clarísima y decidiste ignorar? Cuéntala o bebe 2'),
    Tile(id: 902, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Cuenta una discusión absurda que tuviste en pareja o bebe 2'),
    Tile(id: 903, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Alguna vez has cotilleado las redes de tu ex después de dejarlo? Confiesa o bebe 2'),
    Tile(id: 904, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Te han dejado o has dejado más veces? Explica o bebe 2'),
    Tile(id: 905, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Cuenta algo que hiciste en una relación que repetirías sin dudarlo, o bebe 2'),
    Tile(id: 917, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Cuánto tardaste en stalkear a tu ex después de la ruptura? Confiesa o bebe 2'),
    Tile(id: 918, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Has usado a alguien como rebote? Cuenta o bebe 2'),
    Tile(id: 919, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Alguna vez has fingido estar bien después de una ruptura? ¿Cuánto duró la farsa? Cuéntalo o bebe 2'),
    Tile(id: 920, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Has bloqueado y desbloqueado a alguien más de una vez? Explica por qué o bebe 2'),
    Tile(id: 921, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Cuenta la ruptura más cobarde que has tenido, dando o recibiendo, o bebe 2'),
    Tile(id: 922, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Has mandado un "feliz cumpleaños" a un ex solo para ver si respondía? Confiesa o bebe 2'),
    Tile(id: 923, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: '¿Alguna vez has puesto una canción en un plan para que alguien concreto la escuchara? Cuenta o bebe 2'),

    // WILD
    Tile(id: 906, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Volverías con tu ex si te escribe ahora mismo? Responde sin pensar o bebe 2'),
    Tile(id: 907, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta lo más rastrero que hiciste por celos o bebe 3'),
    Tile(id: 908, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿A quién de tus ex no soportas ver feliz? Di el nombre o bebe 3'),
    Tile(id: 909, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has hablado con alguien solo para dar celos? Cuenta o bebe 3'),
    Tile(id: 910, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta una mentira que dijiste en una relación de la que nunca se enteraron, o bebe 3'),
    Tile(id: 911, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has mirado el móvil de alguien a escondidas? Cuenta qué encontraste o bebe 3'),
    Tile(id: 912, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿A quién de aquí crees que sería el ex más tóxico? Señálalo o bebe 3'),
    Tile(id: 913, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta lo más humillante que hiciste por alguien que te gustaba, o bebe 3'),
    Tile(id: 914, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has vuelto con alguien solo por no estar solo? Cuenta o bebe 3'),
    Tile(id: 924, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿A cuántos ex has stalkeado esta semana? Número real o bebe 3'),
    Tile(id: 925, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Cuál de tus ex ha mejorado más desde que lo dejasteis? Di el nombre o bebe 3'),
    Tile(id: 926, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta lo más patético que hiciste para intentar recuperar a alguien, o bebe 3'),
    Tile(id: 927, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has escrito un mensaje a un ex y lo has borrado sin enviar? Lee lo que ibas a mandar o bebe 3'),
    Tile(id: 928, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has hecho algo solo para que tu ex lo viera en redes? Cuenta o bebe 3'),
    Tile(id: 929, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has quedado con un ex "para hablar" sabiendo que no era solo para hablar? Cuenta o bebe 3'),
    Tile(id: 930, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Di el nombre del ex con el que peor acabaste o bebe 3'),
    Tile(id: 931, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Qué es lo peor que te han dicho en una ruptura? Cuéntalo o bebe 2'),
    Tile(id: 932, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Alguna vez has esperado que tu ex lo pasara mal después de dejarlo? Sé honesto/a o bebe 3'),
    Tile(id: 933, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Cuenta la excusa más ridícula que usaste para terminar con alguien o bebe 3'),
    Tile(id: 934, type: TileType.social, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: '¿Has pedido perdón a un ex sin sentirlo de verdad? ¿Para qué? Cuéntalo o bebe 3'),

    // YO NUNCA
    Tile(id: 935, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he borrado conversaciones para que mi pareja no las viera. El que sí, bebe'),
    Tile(id: 936, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he dado like a fotos antiguas de alguien para que se diera cuenta. El que sí, bebe'),
    Tile(id: 937, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he seguido viendo a alguien sabiendo que no tenía futuro. El que sí, bebe'),
    Tile(id: 938, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Yo nunca he visto las stories de mi ex desde una cuenta falsa. El que sí, bebe'),
    Tile(id: 939, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he terminado con alguien por WhatsApp. El que sí, bebe'),
    Tile(id: 940, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he usado el "necesito tiempo" para no dar una explicación real. El que sí, bebe'),
    Tile(id: 941, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Yo nunca he hablado mal de mi ex con sus propios amigos. El que sí, bebe'),
    Tile(id: 942, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he comparado a mi pareja con un ex en voz alta. El que sí, bebe'),
    Tile(id: 943, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he seguido a la nueva pareja de mi ex en redes para ver cómo es. El que sí, bebe'),
    Tile(id: 944, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Yo nunca he dejado en visto a alguien aposta para hacerle sufrir. El que sí, bebe'),
    Tile(id: 945, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Yo nunca he vuelto con alguien solo porque la nueva relación me daba más miedo. El que sí, bebe'),

    // CAOS
    Tile(id: 915, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Elige a alguien. Durante un turno sois ex tóxicos y discutís'),
    Tile(id: 916, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Todos dicen una red flag en 5 segundos. El que se quede en blanco, bebe'),
    Tile(id: 946, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'El jugador a tu izquierda te manda un audio de voz de 10 segundos como si fuera tu ex tóxico ahora mismo'),
    Tile(id: 947, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'Todos escriben el nombre de su ex más tóxico en el móvil. El que no quiera, bebe 3'),
    Tile(id: 948, type: TileType.chaos, mode: GameMode.wild, pack: ContentPack.exToxico,
        text: 'El grupo elige quién tiene el historial de relaciones más desastroso. Esa persona cuenta su peor historia o bebe 4'),
    Tile(id: 949, type: TileType.chaos, mode: GameMode.spicy, pack: ContentPack.exToxico,
        text: 'Todos en voz alta: ¿en tu última relación eras más tóxico/a tú o la otra persona? El grupo vota quién miente'),
  ];

  // Pack privado — solo se compila con: flutter build --dart-define=PRIVATE_PACK=true
  static const List<Tile> amigos = bool.fromEnvironment('PRIVATE_PACK')
      ? [
          // ── QUÉ PREFIERES ──────────────────────────────────────────────
          Tile(id: 950, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: tener penes en lugar de dedos o vaginas en las palmas de las manos?"),
          Tile(id: 951, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: un buen sexo oral de tu abuela/o que dure poco o un mal sexo oral de tu abuela/o que dure mucho?"),
          Tile(id: 952, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a tu madre/padre en el cuerpo de tu pareja o al revés?"),
          Tile(id: 953, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: el juego del hobbit o al tío Juan Carlos?"),
          Tile(id: 954, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: tener un orgasmo sonoro cada vez que estornudes o cagarte encima cada vez que toses?"),
          Tile(id: 955, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a Josito o no?"),
          Tile(id: 956, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: no volver a salir de tu casa nunca más o ser un vagabundo de la Azohía?"),
          Tile(id: 957, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: que las manos te huelan como pies sudados o que el aliento te huela a pozo negro?"),
          Tile(id: 958, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: ser zoofílico o necrófilo?"),
          Tile(id: 959, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: una patada en los cojones o dos?"),
          Tile(id: 960, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: correrte en 5 segundos o tardar 3 horas?"),
          Tile(id: 961, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a un furro o a un therian?"),
          Tile(id: 962, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: mandar una foto íntima al grupo familiar o que te la envíe a ti tu madre?"),
          Tile(id: 963, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: una paja ajena o mamada propia?"),
          Tile(id: 964, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: ser Spiderman o Miguel Carcaño?"),
          Tile(id: 965, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Qué prefieres: borrar tu peor recuerdo o volver a vivir el mejor?"),
          Tile(id: 966, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: follarte a la Falete o a la Marrash?"),
          Tile(id: 967, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: casarte con Dalas o con Jpelirrojo?"),
          Tile(id: 968, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: salir con el Xokas o con Rickyedit?"),
          Tile(id: 969, type: TileType.social, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Qué prefieres: sopa de murciélago o sopa de cobaya?"),
          Tile(id: 970, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: 5000€ al mes pero comer mierda una vez al mes, o 3000€ al mes por beber un poco de pis una vez a la semana?"),
          Tile(id: 971, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: ser acosado sexualmente en el trabajo o ser acosado laboralmente en el sexo?"),
          Tile(id: 972, type: TileType.social, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Qué prefieres: quedarte embarazado/a con un beso o embarazar a alguien con un beso?"),

          // ── YO NUNCA ────────────────────────────────────────────────────
          Tile(id: 973, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he cagado encima. El que sí, bebe."),
          Tile(id: 974, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he sentido atraído/a por el padre o la madre de un amigo/a. El que sí, bebe."),
          Tile(id: 975, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho un trío con un chino y un inglés (qué específico). El que sí, bebe."),
          Tile(id: 976, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he follado a Josito. El que sí, bebe."),
          Tile(id: 977, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he salido o me he follado a alguien por compromiso. El que sí, bebe."),
          Tile(id: 978, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca le he cagado la polla a alguien. El que sí, bebe."),
          Tile(id: 979, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me liaría con Danny DeVito. El que sí, bebe."),
          Tile(id: 980, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he lamido un sobaco ajeno... o propio. El que sí, bebe."),
          Tile(id: 981, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he lamido pies. El que sí, bebe."),
          Tile(id: 982, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he pensado en otra persona mientras follaba. El que sí, bebe."),
          Tile(id: 983, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he mentido sobre hacer trampas en un juego. El que sí, bebe."),
          Tile(id: 984, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho una paja con los pies. El que sí, bebe."),
          Tile(id: 985, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he fingido un orgasmo. El que sí, bebe."),
          Tile(id: 986, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he meado en una piscina ajena. El que sí, bebe."),
          Tile(id: 987, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he hecho una cuenta falsa para stalkear a alguien. El que sí, bebe."),
          Tile(id: 988, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he follado con la regla. El que sí, bebe."),
          Tile(id: 989, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he disfrazado para hacer el acto sexual. El que sí, bebe."),
          Tile(id: 990, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho una paja en un lugar público. El que sí, bebe."),
          Tile(id: 991, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he follado en la cama de la abuela. El que sí, bebe."),
          Tile(id: 992, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he follado en casa ajena. El que sí, bebe."),
          Tile(id: 993, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he follado y me he arrepentido al terminar. El que sí, bebe."),
          Tile(id: 994, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he dicho que iba a acabar bien con mi ex y luego ha ido como la mierda. El que sí, bebe."),
          Tile(id: 995, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he tenido sexo anal y ha salido hecha un mikado. El que sí, bebe."),
          Tile(id: 996, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he metido fruta o verdura por el culo. El que sí, bebe."),
          Tile(id: 997, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he estado enamorado/a de verdad. El que sí, bebe."),
          Tile(id: 998, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca me he masturbado después de follar por no quedar satisfecho/a. El que sí, bebe."),
          Tile(id: 1000, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he querido a dos personas a la vez. El que sí, bebe."),
          Tile(id: 1001, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho un Simba. El que sí, bebe."),
          Tile(id: 1002, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he criticado a un amigo/a con otro amigo/a del mismo grupo. El que sí, bebe."),
          Tile(id: 1003, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he robado ropa interior. El que sí, bebe."),
          Tile(id: 1004, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he ido a una orgía. El que sí, bebe."),
          Tile(id: 1005, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he lamido un pene o chochito que olía a cadáver. El que sí, bebe."),
          Tile(id: 1006, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he hecho cruising. El que sí, bebe."),
          Tile(id: 1007, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "Yo nunca he ido a una sauna gay. El que sí, bebe."),
          Tile(id: 1008, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he tomado una castaña más mala que la mierda en el Pedrotito. El que sí, bebe."),
          Tile(id: 1009, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he tonteado con alguien sabiendo que tenía pareja. El que sí, bebe."),
          Tile(id: 1010, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca me he liado con un amigo/a. El que sí, bebe."),
          Tile(id: 1011, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he zorreado con alguien para darle celos a otra persona. El que sí, bebe."),
          Tile(id: 1012, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "Yo nunca he robado algo de más de 10 euros. El que sí, bebe."),

          // ── QUIÉN ES MÁS PROBABLE ───────────────────────────────────────
          Tile(id: 1013, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que mame pito esta noche? El grupo señala. El más señalado bebe."),
          Tile(id: 1014, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que NO mame pito esta noche? El grupo señala. El más señalado bebe."),
          Tile(id: 1015, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que salga en un vídeo de Trakatá? El grupo señala. El más señalado bebe."),
          Tile(id: 1016, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que ponga una excusa para no venir a un plan? El grupo señala. El más señalado bebe."),
          Tile(id: 1017, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se pique por una tontería? El grupo señala. El más señalado bebe."),
          Tile(id: 1018, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se folle a Josito? El grupo señala. El más señalado bebe."),
          Tile(id: 1019, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que golpee un perro? El grupo señala. El más señalado bebe."),
          Tile(id: 1020, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que patee un gato? El grupo señala. El más señalado bebe."),
          Tile(id: 1021, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que abofetee un hámster? El grupo señala. El más señalado bebe."),
          Tile(id: 1022, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que mate un canguro? El grupo señala. El más señalado bebe."),
          Tile(id: 1023, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se lleve un arroz con voces? El grupo señala. El más señalado bebe."),
          Tile(id: 1024, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que acabe en una trieja? El grupo señala. El más señalado bebe."),
          Tile(id: 1025, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se vuelva viral en redes? El grupo señala. El más señalado bebe."),
          Tile(id: 1026, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que dé más vergüenza estando borracho/a? El grupo señala. El más señalado bebe."),
          Tile(id: 1027, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se grabe follando? El grupo señala. El más señalado bebe."),
          Tile(id: 1028, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que le revise el móvil a su pareja? El grupo señala. El más señalado bebe."),
          Tile(id: 1029, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que salga con la expareja de un amigo/a? El grupo señala. El más señalado bebe."),
          Tile(id: 1030, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que tenga una relación abierta en Madrid? El grupo señala. El más señalado bebe."),
          Tile(id: 1031, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a Skin y se le corran en la espalda? El grupo señala. El más señalado bebe."),
          Tile(id: 1032, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a la casa de los gemelos? El grupo señala. El más señalado bebe."),
          Tile(id: 1033, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se cambie de acera? El grupo señala. El más señalado bebe."),
          Tile(id: 1034, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a la isla de las tentaciones? El grupo señala. El más señalado bebe."),
          Tile(id: 1035, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que acabe haciendo cruising donde el Tracatrá? El grupo señala. El más señalado bebe."),
          Tile(id: 1036, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya a una sauna gay? El grupo señala. El más señalado bebe."),
          Tile(id: 1037, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que venda fotos de los pies? El grupo señala. El más señalado bebe."),
          Tile(id: 1038, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que no responda al WhatsApp? El grupo señala. El más señalado bebe."),
          Tile(id: 1039, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se quede dormido/a antes de un evento importante? El grupo señala. El más señalado bebe."),
          Tile(id: 1040, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se case primero? El grupo señala. El más señalado bebe."),
          Tile(id: 1041, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se abra un OnlyFans? El grupo señala. El más señalado bebe."),
          Tile(id: 1042, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que sea infiel? El grupo señala. El más señalado bebe."),
          Tile(id: 1043, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que acabe en una secta? El grupo señala. El más señalado bebe."),
          Tile(id: 1044, type: TileType.groupDrink, mode: GameMode.spicy, pack: ContentPack.amigos,
              text: "¿Quién es más probable que vaya al espacio? El grupo señala. El más señalado bebe."),
          Tile(id: 1045, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que se meta a monja o cura? El grupo señala. El más señalado bebe."),
          Tile(id: 1046, type: TileType.groupDrink, mode: GameMode.wild, pack: ContentPack.amigos,
              text: "¿Quién es más probable que sea captado por una secta? El grupo señala. El más señalado bebe."),
        ]
      : [];

  static const Tile finale = Tile(
    id: 999,
    type: TileType.finale,
    text: '¡BRONCOLA FINAL!',
  );
}
